server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://117.50.179.8/file
    username: root
    password: fghf987....
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  file:
    name: D:\code\java\springboot\fireshare\src\main\resources\logs\web.log
  level:
    root: info