server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://117.50.179.8/file
    username: root
    password: fghf987....
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
file:
  storage-type: 0
mybatis-plus:
  mapper-locations:
    - classpath:/mapper/**.xml